name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang, mingw, msvc]
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: mingw
          - os: ubuntu-latest
            compiler: msvc

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure (CMake Presets)
      run: cmake --preset=${{ matrix.compiler }}-debug

    - name: Build
      run: cmake --build --preset=build-debug

    - name: Run tests
      run: ctest --preset=test-debug --output-on-failure
